### ISSUE TITLE
Support for Intel GPUs is outdated

### ISSUE THREAD

**Issue by Cacodemon345** [illumos/gfx-drm#24]
Support for Intel GPUs have been outdated by many years; Broadwell and later isn't supported at all even after 7 years. The rest of the Unix open source operating system projects is catching up to upstream Linux GPU support meanwhile.

At least update the support of Intel GPUs to at least Skylake.

**Comment by mcendu** [comment]
This repo seems to be dead. Is there any hope of syncing with [Linux]'s state?

[Linux]: https://www.kernel.org/

**Comment by gwr** [comment]
Complaining is not helpful.
